const KeyMap = {
	'Backspace': 'K_BACKSPACE',
	'Tab': 'K_TAB',
	'Clear': 'K_CLEAR',
	'Enter': 'K_RETURN',
	'Pause': 'K_PAUSE',
	'Escape': 'K_ESCAPE',
	' ': 'K_SPACE',
	'!': 'K_EXCLAIM',
	'"': 'K_QUOTEDBL',
	'#': 'K_HASH',
	'$': 'K_DOLLAR',
	'&': 'K_AMPERSAND',
	'\'': 'K_QUOTE',
	'(': 'K_LEFTPAREN',
	')': 'K_RIGHTPAREN',
	'*': 'K_ASTERISK',
	'+': 'K_PLUS',
	',': 'K_COMMA',
	'-': 'K_MINUS',
	'.': 'K_PERIOD',
	'/': 'K_SLASH',
	'0': 'K_0', '1': 'K_1', '2': 'K_2', '3': 'K_3', '4': 'K_4',
	'5': 'K_5', '6': 'K_6', '7': 'K_7', '8': 'K_8', '9': 'K_9',
	':': 'K_COLON',
	';': 'K_SEMICOLON',
	'<': 'K_LESS',
	'=': 'K_EQUALS',
	'>': 'K_GREATER',
	'?': 'K_QUESTION',
	'@': 'K_AT',
	'[': 'K_LEFTBRACKET',
	'\\': 'K_BACKSLASH',
	']': 'K_RIGHTBRACKET',
	'^': 'K_CARET',
	'_': 'K_UNDERSCORE',
	'`': 'K_BACKQUOTE',
	'a': 'K_a', 'b': 'K_b', 'c': 'K_c', 'd': 'K_d', 'e': 'K_e', 'f': 'K_f',
	'g': 'K_g', 'h': 'K_h', 'i': 'K_i', 'j': 'K_j', 'k': 'K_k', 'l': 'K_l',
	'm': 'K_m', 'n': 'K_n', 'o': 'K_o', 'p': 'K_p', 'q': 'K_q', 'r': 'K_r',
	's': 'K_s', 't': 'K_t', 'u': 'K_u', 'v': 'K_v', 'w': 'K_w', 'x': 'K_x',
	'y': 'K_y', 'z': 'K_z',
	'Delete': 'K_DELETE',
	'Insert': 'K_INSERT',
	'Home': 'K_HOME',
	'End': 'K_END',
	'PageUp': 'K_PAGEUP',
	'PageDown': 'K_PAGEDOWN',
	'ArrowUp': 'K_UP',
	'ArrowDown': 'K_DOWN',
	'ArrowLeft': 'K_LEFT',
	'ArrowRight': 'K_RIGHT',
	'F1': 'K_F1', 'F2': 'K_F2', 'F3': 'K_F3', 'F4': 'K_F4', 'F5': 'K_F5',
	'F6': 'K_F6', 'F7': 'K_F7', 'F8': 'K_F8', 'F9': 'K_F9', 'F10': 'K_F10',
	'F11': 'K_F11', 'F12': 'K_F12', 'F13': 'K_F13', 'F14': 'K_F14', 'F15': 'K_F15',
	'NumLock': 'K_NUMLOCK',
	'CapsLock': 'K_CAPSLOCK',
	'ScrollLock': 'K_SCROLLOCK',
	'ShiftRight': 'K_RSHIFT',
	'ShiftLeft': 'K_LSHIFT',
	'ControlRight': 'K_RCTRL',
	'ControlLeft': 'K_LCTRL',
	'AltRight': 'K_RALT',
	'AltLeft': 'K_LALT',
	'MetaRight': 'K_RMETA',
	'MetaLeft': 'K_LMETA',
	'ContextMenu': 'K_MENU',
	'PrintScreen': 'K_PRINT',
	'Break': 'K_BREAK',
	'Help': 'K_HELP',
	'Power': 'K_POWER',
};

const ModKeyMap = {
	"ShiftLeft": 'K_LSHIFT',
	"ShiftRight": 'K_RSHIFT',
	"ControlLeft": 'K_LCTRL',
	"ControlRight": 'K_RCTRL',
	"AltLeft": 'K_LALT',
	"AltRight": 'K_RALT',
	"MetaLeft": 'K_LMETA',
	"MetaRight": 'K_RMETA',
};

export const maps = {
	KeyMap,
	ModKeyMap
};